# Generated by Django 5.2.5 on 2025-08-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='cpu_percent',
        ),
        migrations.RemoveField(
            model_name='process',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='process',
            name='memory_percent',
        ),
        migrations.AddField(
            model_name='process',
            name='memory',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='process',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
