# Generated by Django 5.2.5 on 2025-08-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_remove_process_cpu_percent_remove_process_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
