# Generated by Django 5.2.5 on 2025-08-24 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_alter_process_name_alter_process_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('pid', models.IntegerField()),
                ('ppid', models.IntegerField(default=0)),
                ('cpu_percent', models.FloatField(default=0.0)),
                ('memory_mb', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('os', models.CharField(blank=True, max_length=255, null=True)),
                ('os_version', models.CharField(blank=True, max_length=255, null=True)),
                ('processor', models.CharField(blank=True, max_length=255, null=True)),
                ('num_cpus', models.IntegerField(default=1)),
                ('num_threads', models.IntegerField(default=1)),
                ('ram_total_gb', models.FloatField(default=0.0)),
                ('ram_used_gb', models.FloatField(default=0.0)),
                ('ram_available_gb', models.FloatField(default=0.0)),
                ('disk_total_gb', models.FloatField(default=0.0)),
                ('disk_used_gb', models.FloatField(default=0.0)),
                ('disk_free_gb', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.AddField(
            model_name='processinfo',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='backend_app.systeminfo'),
        ),
    ]
